"""Add relationships and validations

Revision ID: d9d6e3387be7
Revises: c7794d98348c
Create Date: 2025-04-15 23:35:50.841244

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9d6e3387be7'
down_revision = 'c7794d98348c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
